### ISSUE TITLE
Don't support async components?

### ISSUE THREAD

**Issue by lmk123** [framework7io/framework7-vue#114]
I want to use [Async Components](https://vuejs.org/v2/guide/components.html#Async-Components) in my project, but it seems not working correctly:

```js
Vue.component('about-page', () => import('./path/to/about.vue'))

new Vue({
  framework7: {
    routes: [
      {
        path: '/about/',
        component: 'about-page'
      }
    ]
  }
})
```

**Comment by chenzhaoyangATgithub** [comment]
I find it works on PC, but not cellphone

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
