### ISSUE TITLE
pushState - Restoration without animation

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#120]
Kitchen sink:
- pushState: true
- start `npm run dev`
- open a sub page, for example nested routes > tabs

URL will be shown:
http://localhost:8080/#!//nested-routes/tabs/tab-2/

Then, refresh the page ... first page will be shown, then the tabs page with second tab - both with animation.

Could we make the URL restoration without animation at the beginning?

**Comment by jinnanzhao** [comment]
- 

- [ ] #1.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
