### ISSUE TITLE
Refresh sub page fails

### ISSUE THREAD

**Issue by scriptPilot** [framework7io/framework7-vue#122]
I moved the initial page content from the kitchen sink to an extra page "home.vue". Then I opened the kitchen sink - everything is fine. Then I refresh the kitchen sink - everything is fine. Then I opened a sub page and refreshed it - loading fails.

Code changes as pull request: #123  - for testing only.

![bildschirmfoto 2017-03-22 um 16 28 16](https://cloud.githubusercontent.com/assets/19615586/24205759/9acf4dd4-0f1c-11e7-82be-b94de9fb66e6.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
