### ISSUE TITLE
Navbar on RTL - bug

### ISSUE THREAD

**Issue by ttv20** [framework7io/framework7-vue#130]
On RTL language the navbar should be like this:
navbar
    navbar-inner
        right
        center
        left

But, when I use the "back-link" props is automatic left class and the left is before the center/right (it's look bad)
You should add a rtl prop or custom direction with "back-link"

thanks

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
