### ISSUE TITLE
multiple dom element for same page

### ISSUE THREAD

**Issue by SiddiquiImran** [framework7io/framework7-vue#143]
Hi,
When we are working on one of our project we faced very strange issue:
![9bb6483e-29e2-11e7-9fa3-06a6120606a3](https://cloud.githubusercontent.com/assets/20870175/25386158/00b1b1c8-29e4-11e7-8960-b64ca54c6247.png)

As you can refer image there we have a tabstrip and in the last button "more"  a list of other module is opened up so you can go other view.

so if you go to one of view and after that you you went to other view directly without clicking on back button and again went to first view it creates new data-page view and marked old one as cached.

**Repository Url to check: https://github.com/SiddiquiImran/f7vue**

**Comment by SiddiquiImran** [comment]
may be @HoldSkill also facing the same issue: 
https://github.com/nolimits4web/Framework7-Vue/issues/133

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
