### ISSUE TITLE
tracking page enter and page left event 

### ISSUE THREAD

**Issue by SiddiquiImran** [framework7io/framework7-vue#151]
Hi All,

How we can track page enter and page left event in framework 7 vue?

I have tried vue life-cycle event as well as f7 events but it is not working in case if user enter to the different page using bottom tab strip in place of clicking on back button and then go to new page.

Any help, it's urgent !!

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
