### ISSUE TITLE
Issue with <f7-link> creating multiple copies of same page in DOM

### ISSUE THREAD

**Issue by Regulus343** [framework7io/framework7-vue#152]
I'm using <f7-link> to navigate around, but it's creating copies of the same page in the DOM, which is fine in most cases, except where IDs are concerned because of the duplicate elements with the same ID. This means that tabs whose links target IDs no longer work. Is there a way to get Framework7 to only keep one copy of any opened page in the DOM? Is there a reason why it duplicates pages in the DOM the way it does?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
