### ISSUE TITLE
Wrong $route data

### ISSUE THREAD

**Issue by mgesmundo** [framework7io/framework7-vue#153]
The value of $route data correspond to the last visited page instead the data of the page itself. Try using the kitchen-sink and visit some pages (see the images).
Best regards.

Marcello

![document](https://cloud.githubusercontent.com/assets/1668543/25693758/5f9077a6-30ab-11e7-9be2-e06c3a9d89d0.png)

![document](https://cloud.githubusercontent.com/assets/1668543/25693775/77d6ba6e-30ab-11e7-8339-33e18063277d.png)

![document](https://cloud.githubusercontent.com/assets/1668543/25693785/82944eda-30ab-11e7-8144-bba310ebaa17.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
