### ISSUE TITLE
modal-out in actions.vue

### ISSUE THREAD

**Issue by lcaprini** [framework7io/framework7-vue#155]
Hi,
in my `f7-actions` component I'm using `:opened` prop to open and close.
I've noticed that the action sheet's animation works well when I open it and when I click on `modal-overlay`, but if parent component change the `:opened` prop the animation doesn't works.

I tried to change `:class="{'modal-in': opened}"` in `:class="[{'modal-in': opened, 'modal-out': !opened}]"` in `actions.vue` file and now it works correctly everytime.

Can you make this edit in the next release?

Thank you.
--Luca

**Comment by lcaprini** [comment]
In the last release was made an edit in `actions.vue` to add `modal-out` animation, but was also added `self.$el.style.display = 'none'` in `opened` watcher and the animation doesn't work.
I forced `self.$el.style.display = 'block'` and it works correctly.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
