### ISSUE TITLE
"style" is a reserved attribute in "form-input.vue"

### ISSUE THREAD

**Issue by xxxxxMiss** [framework7io/framework7-vue#157]
when i use `<f7-list from>` component, Vue throw a warn `"style" is a reserved attribute and cannot be used as component prop.`

Vue version: `2.2.6`

**Comment by chenzhaoyangATgithub** [comment]
I meet it too. Beg for help

**Comment by JonSmart** [comment]
The code is fixed, but there hasn't been a release so the package installed uses 0.9.0 which has the bug.

**Comment by rvanzon** [comment]
If you want to use it follow these instructies: https://gist.github.com/rvanzon/a83b579d7c0775150ca51c6a3b0a0389

**Comment by KirinHuang** [comment]
I think `npm install -S git+https://github.com/KirinHuang/Framework7-Vue.git` is more easier, OR you can just fork the project and build for own repository and `npm install -S git+https://github.com/YOURNAME/Framework7-Vue.git`. It's more controllable!

**Comment by chenzhaoyangATgithub** [comment]
Oh，thank you. This warning I think is tolerable. So I choose to ignore it

**Comment by KirinHuang** [comment]
Yes, it's not a functionality issue

**Comment by chenzhaoyangATgithub** [comment]
npm install -S git+https://github.com/KirinHuang/Framework7-Vue.git 

unluckily . it seems that the problem steal exists

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
