### ISSUE TITLE
When the function "$router.back ({})" is executed, the URL in the address bar does not change

### ISSUE THREAD

**Issue by araimbekoff** [framework7io/framework7-vue#161]
I want to go 2 pages back. I determined which page this is on page init. 
when 
this.$router.back({url:'my-page-path'})
the page goes back, but the address bar remains unchanged.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
