### ISSUE TITLE
select MULTIPLE result not show in smart-selector with dynamic options

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#164]
```
<template>
	<f7-page>
		<f7-navbar back-link="Voltar" title="Seleção para Contestação" sliding></f7-navbar>

		<f7-list form>
			<f7-list-item smart-select smart-select-searchbar smart-select-searchbar-placeholder="Pesquisar operações" title="Operações">
				<select v-model="selectedItems" name="operations" multiple="multiple">
					<optgroup v-for="operation in operations" :label="operation.text">
						<option v-for="item in operation.children" :value="item.id" selected>{{item.text}}</option>
					</optgroup>
				</select>
			</f7-list-item>
		</f7-list>
	</f7-page>
</template>

<script>
	export default
		{
			data: function()
			{
				return {
					selectedItems: ["10200", "10400"],
					operations: []
				};
			},

			created: async function()
			{
				this.operations = await httpGet("Operations");
			}
		}
</script>
```

The data is loaded, the items 10200 and 10400 are sucessfully selected (when the select is shown), but the selected items NEVER appears on the form. =\

![untitled](https://cloud.githubusercontent.com/assets/379339/26126171/0477142e-3a5b-11e7-88ad-55e3daddb704.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
