### ISSUE TITLE
how to open one vue with different param

### ISSUE THREAD

**Issue by ijry** [framework7io/framework7-vue#165]
![qq 20170518184626](https://cloud.githubusercontent.com/assets/3102798/26199154/8ec46aae-3bfb-11e7-8fef-42ba6bc255c5.png)

when i at page 1, i clicked 2 ,but nothing happened;

**Comment by rvanzon** [comment]
@ijry did you use `f7-link`? The hashbang is missing.

**Comment by ijry** [comment]
hashbang?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
