### ISSUE TITLE
how i can send Dom7.ajax request  with async=false?

### ISSUE THREAD

**Issue by araimbekoff** [framework7io/framework7-vue#179]
if send request as `async:false` then warn 
`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its... bla bla bla`.

And yet, there are cases when there is a need for a synchronous request.
What solution is there?

**Comment by Matheo13** [comment]
async:false is a depreciation of w3c, no relation with this framework.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
