### ISSUE TITLE
binding radio to undefined

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7-vue#181]
I am getting the error: Cannot read property 'toString' of undefined.
I have the following:
`    <f7-list-item radio name="my-radio" input-value=undefined title="None" v-model="tape"></f7-list-item>
    <f7-list-item radio name="my-radio" input-value="yellow" title="Yellow" v-model="tape"></f7-list-item>
`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
