### ISSUE TITLE
Vue warn

### ISSUE THREAD

**Issue by kevin-wang-online** [framework7io/framework7-vue#188]
After the installation from the website, the browser console a error, please help 

vue.esm.js?65d7:434 [Vue warn]: Error in mounted hook: "TypeError: e.reduce is not a function"

**Comment by tboztuna** [comment]
I have the same issue.

**Comment by ddtramp** [comment]
@tboztuna @kevin-wang-online  check router in framework7 init params
the router is Array
the vue router is vue-Router instance

**Comment by PHEOBUSYY** [comment]
@ddtramp thank you !

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
