### ISSUE TITLE
Nested Route Tabbar Highlight

### ISSUE THREAD

**Issue by dstrang** [framework7io/framework7-vue#189]
I think this only affects the material theme.

When using a tabbar with nested routes, the styling and highlight are not applied. See images below.

![tabbar_highlight](https://user-images.githubusercontent.com/5985749/26890940-29031554-4b68-11e7-9d1b-26432198653c.png)
![nested_tabbar](https://user-images.githubusercontent.com/5985749/26890949-2db45f18-4b68-11e7-933c-718b528ba081.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
