### ISSUE TITLE
Don't support async components?

### ISSUE THREAD

**Issue by yijiaqingilm** [framework7io/framework7-vue#192]
I want to use Async Components in my project, but it seems not working correctly:

const About= resolve => {
    require.ensure([], () => {
        resolve(require('./path/to/about.vue'))
    })

}

new Vue({
  framework7: {
    routes: [
      {
        path: '/about/',
        component: About
      }
    ]
  }
})

**Comment by yijiaqingilm** [comment]
I found that as long as the returns of component information from asynchronous execution of switch then the page when there are problems

**Comment by yijiaqingilm** [comment]
I found that as long as the returns of component information from asynchronous execution of switch then the page when there are problems

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
