### ISSUE TITLE
Navigation do not work in Google Android emulator

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7-vue#195]
Used the cordova webpack template (cordova create <project_create_dir> [com.example.projectname] [ProjectClassName] --template cordova-template-framework7-vue-webpack).

Just run with cordova run android -- --lr.

On Google Emulator (AVD), links won't navigate. The sidebars work, the ripple effect work, but nothing happens when I touch the links. Live reload also work fine. 

In browser and real android everything works just fine.

How can I know what is going on? =\

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
