### ISSUE TITLE
nested links changes this

### ISSUE THREAD

**Issue by lroal** [framework7io/framework7-vue#196]
I have a problem with routing and this keyword. When one Component A links to another component B, it actually sets **componentA.this = componentB.this.** 
What is going on ?

And when using same props name in two different routes, it complains about duplicates: _The data property "id" is already declared as a prop. Use prop default value instead._
My routes:
```
{
    path: '/a/:id',
      component: require('./a.vue')
  },
  {
      path: '/b/:id',
      component: require('./b.vue')
  },

```

**Comment by lroal** [comment]
I seems like almost all open issues are related to routing. The root problem is that the **this** object is somehow shared between pages. This is not good.

F7 is a fantastic framework except for the routing - which is buggy. Maybe consider using the standard router in vue instead ?

**Comment by lroal** [comment]
Any news on this one or #167 ?
I can hack a workaround by letting component b have it's id in position 2 and let position 1 contain the id of a.

**Comment by lroal** [comment]
another workaround in the component:
```
data : function() {
      this._id = this.id;
      return {};
}
```

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
