### ISSUE TITLE
the vue components reloading by using f7 router

### ISSUE THREAD

**Issue by huangyuanyazi** [framework7io/framework7-vue#197]
for example:
A page link to B page and B page link to A page ,the element in the browser show a lot of elements contain  
class cached

**Comment by TangOwen** [comment]
Because too much content will stays on the DOM, it can affect performance. I'm also paying attention to this problem. Is there a official solution?

**Comment by huangyuanyazi** [comment]
Bind ':domCache=false' on the 'f7-view' can be resoved and no other problems were found for the time being

**Comment by TangOwen** [comment]
Thanks for the tip. Yes, but I can't go back to my home page. It should be the routing record because the home page is rendered directly in the app.vue

**Comment by huangyuanyazi** [comment]
Can't all pages be routed back?Again, you return multiple levels with routing

**Comment by TangOwen** [comment]
Similar to the official webpack case. The home page is rendered directly in app.vue, not in the routing. So when I enter the page B from **page A**(home page), enter the page C from page B. I can't go back to **page A**

**Comment by huangyuanyazi** [comment]
I see what you mean.You can set an empty page on the App.vue and the empty page are routed to the home page

**Comment by TangOwen** [comment]
That's true, but it's not very elegant.

**Comment by huangyuanyazi** [comment]
Yes, but i haven't found a better solution yet

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
