### ISSUE TITLE
this.$router.back({force: true, url: '/user/index/index/'});

### ISSUE THREAD

**Issue by ijry** [framework7io/framework7-vue#201]
this really has strange bugs

**Comment by ijry** [comment]
![qq 20170622221150](https://user-images.githubusercontent.com/3102798/27438429-cff6cdb6-5797-11e7-839e-ebcdef03f1ff.png)
![toggle](https://user-images.githubusercontent.com/3102798/27438430-d01ba320-5797-11e7-9cd7-da0c9c3e21f5.gif)

**Comment by ijry** [comment]
@macdonst @devgeeks @nolimits4web @GuillaumeBiton @orangeShadow   SOS   ... — — — ...

**Comment by edgardleal** [comment]
Please see the issue #202

**Comment by joseph2002** [comment]
use url to back is buggy, but pagename seems to be ok, try this.$router.back({force: true, pageName: 'xxx'});

**Comment by ijry** [comment]
pageName cannot work, but I find the problem, if Set :domCache="true" ,then this.$router.back({force: true, url: '/user/index/index/'});  worked , if Set :domCache="false", the bug will show @joseph2002 @edgardleal

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
