### ISSUE TITLE
is there a way to solve this case?

### ISSUE THREAD

**Issue by ijry** [framework7io/framework7-vue#202]
![login](https://user-images.githubusercontent.com/3102798/27479334-25a0b494-5846-11e7-9ff1-13c1b6e81096.gif)

after login success how to refresh pre page just like usercenter page.

**Comment by ijry** [comment]
tryed every methods even like this:
![qq 20170623201115](https://user-images.githubusercontent.com/3102798/27481641-3047a3da-5850-11e7-9e7c-0cf6573632ad.png)

**Comment by edgardleal** [comment]
Have you tried use `mainView`? 
` self.$f7.mainView.router.refreshPage();`
I had some problems using the route of a non `mainView`.

**Comment by ijry** [comment]
i have tryed brfore, also donn't worked.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
