### ISSUE TITLE
tab active disappears when back to page

### ISSUE THREAD

**Issue by joseph2002** [framework7io/framework7-vue#205]
this happened when navigate from pageA(contains nested route for tabs) to pageB(also contains nested route for tabs), and then back to pageA. no tab is active on pageA now.
also happened for tabbed views, when one view contains tabbed routes, then navigate to another view which contains another tabbed routes, and switch back to former view.
the chrome inspector shows that the former page's tab active class removed while entering later page

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
