### ISSUE TITLE
Nested Routes not selected tab1 

### ISSUE THREAD

**Issue by sunflowerlb** [framework7io/framework7-vue#212]
![image](https://user-images.githubusercontent.com/3375814/27989148-e7a7d778-6464-11e7-8ccc-004cef365f7e.png)

In 0.9.2 version can not be selected by default tab1. But in 0.8.5 version can be selected.
Click on the tab1 link, the tab1 content also show. @nolimits4web

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
