### ISSUE TITLE
issue with navbar in a popup in a subpage

### ISSUE THREAD

**Issue by yupeilin123** [framework7io/framework7-vue#213]
On one page, the pop-up box is implemented with popup, and the popup navigation bar appears on the page instead of the pop-up itself. I downloaded a sample of framework7 vue. And on the inside of the about page, a test was done.
[Framework7-Vue-popup.zip](https://github.com/nolimits4web/Framework7-Vue/files/1147176/Framework7-Vue-popup.zip)

**Comment by yupeilin123** [comment]
![1ef0d812e99afdda547515d6ccb12ee](https://user-images.githubusercontent.com/28672197/28206456-8e02f34e-68b8-11e7-95fa-13d969b9d102.png)
![6793a89eab33e7a1e1643a0b828a8bc](https://user-images.githubusercontent.com/28672197/28206461-902c0b1a-68b8-11e7-8ae2-f94de2e023cc.png)
![cd79c6878dd347c5741157fd8a2dc6f](https://user-images.githubusercontent.com/28672197/28206462-922f1f92-68b8-11e7-8654-4b73adb8b2f1.png)
![e1ce81b7e21995d9ce7b60f024a631e](https://user-images.githubusercontent.com/28672197/28206465-956af5d2-68b8-11e7-8cd6-58f85bc040bc.png)

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
