### ISSUE TITLE
framework7-vue's route problem

### ISSUE THREAD

**Issue by yangbin932** [framework7io/framework7-vue#250]
<f7-views>
      <f7-view main id="main-view" navbar-through :dynamic-navbar="true" url="/hello">
        <f7-pages></f7-pages>
      </f7-view>
</f7-views>

I can't solve the problem as follows:
[Vue warn]: Failed to mount component: template or render function not defined.

**Comment by decates** [comment]
@yangbin932 - How are you referencing the component in your routes array? Could you include some code? Or did you manage to fix this?

**Comment by jamesnw** [comment]
I had this issue after upgrading `vue-loader` to > v13.0.0. There are breaking changes with how modules are imported, meaning the component can not simply be required as it used to be. I had this: 

```
{
	path: '/app/:appId',
	component: require('path/to/app.vue')
},
```

I replaced it with: 
```
import App from '/path/to/app.vue'
{
	path: '/app/:appId',
	component: App
},
```

I think this would also work: 
```
{
	path: '/app/:appId',
	component: require('path/to/app.vue').default
},
```

See more in the breaking changes here- https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual/needed more information/inactivity.

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
