### ISSUE TITLE
Change min and max Date dynamically in Calendar vue

### ISSUE THREAD

**Issue by karymont** [framework7io/framework7-vue#266]
Hi, Im trying to change props 'minDat'e and 'maxDate' dinamically after a user selects a day. 
So far it works with the assigned values when the component is created, but whenever I try to update those values they have no effect in calendar component.
Ex.

`<f7-calendar :range-picker= "true" :minDate="min" :maxDate="max"  @change="changeDate"/>

changeDate: function (c, values, displayValues) {
  this.min = '2017-11-10'
  this.max = '2017-12-12'
}`

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual for current v2 release

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
