### ISSUE TITLE
 [Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by varunajmera0** [framework7io/framework7-vue#276]
![image](https://user-images.githubusercontent.com/22893376/32480021-b8f0e5ac-c3b2-11e7-9011-e397b2960061.png)

**Comment by varunajmera0** [comment]
Go to package.json
update ur framework7-vue dependency
"dependencies": {
"framework7": "^1.5.2",
"framework7-vue": "^0.9.2",
"vue": "^2.1.0"
}
It will work fine.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
