### ISSUE TITLE
select result not show in smart-selector with dynamic options

### ISSUE THREAD

**Issue by jqs7** [framework7io/framework7-vue#32]
code:
```js
<f7-list-item smart-select smart-select-back-on-select title="test">
        <select v-model="type">
          <option v-for="(v,i) in types" :value="i">{{v}}</option>
        </select>
</f7-list-item>

    data: function () {
      return {
        type: 0,
        types:{},
      }
    }
    
    mounted(){
        setTimeout(() => {this.types = ['1','2','3']},3000)
    }
```

**Comment by davigmacode** [comment]
use a default options, it works for me.

```
data: function () {
  return {
    types: ['1']
  }
}
```

it happen because this element not automatically created without a default options

```
<div class="item-after">option label</div>
```

**Comment by zhennann** [comment]
thanks.

**Comment by nameit** [comment]
thanks

**Comment by KirinHuang** [comment]
+1

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
