### ISSUE TITLE
where is calendar ？

### ISSUE THREAD

**Issue by evolutionjay** [framework7io/framework7-vue#429]
vue f7 has no calendar component ？

**Comment by nolimits4web** [comment]
Your issue is closed because it is not filled correctly. Before you open an issue please review the [contributing guideline](https://github.com/framework7io/framework7/blob/master/CONTRIBUTING.md).

Please fill the issue template correctly and:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with isssue

It will save a lot of time for other contributors to check your issue and fix it.

> Do you want to ask a question? Are you looking for support? The [Framework7 forum](http://forum.framework7.io/) and [Stack Overflow](http://stackoverflow.com/questions/tagged/framework7) are the best places for getting support

> Please, don't use GitHub issues for questions
