### ISSUE TITLE
Passing data back between pages.

### ISSUE THREAD

**Issue by shaokun** [framework7io/framework7-vue#64]
The F7-Vue router is different from the Vue one, so it's difficult to follow the standard "props down, events up". A developer has to pass data into the next page by using the url query. While in the back direction, it seems no easy way to pass data back to the previous page.

Is there a way to support passing data back to the previous page?

**Comment by centrual** [comment]
You can use [Vuex](https://github.com/vuejs/vuex) for that.

**Comment by red010182** [comment]
Can we just use Vue-Router instead of F7-Vue router?

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7 & Framework7-Vue, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
